### PR TITLE
Up option for xdebug profiling

### PR DESCRIPTION
**Pull request by mrclay**
Enables the option in https://github.com/forumone/generator-web-starter/pull/221

### CODE REVIEW

**Comment by gustavderdrache** [comment]
Is there any chance we'd want to use debugging and profiling at the same time? I'm wondering if we wouldn't be better served by unifying these options:

* `f1 up` - normal
* `f1 up --xdebug` - enables step debugging
* `f1 up --xdebug=profile` enables profiling

**Comment by mrclay** [comment]
@gustavderdrache I got time to do that.

**Comment by mrclay** [comment]
@gustavderdrache I found no way to have a flag with optional argument; it's either boolean or requires an arg. It allows a parse() argument but it validates before calling it.

The best we could do without fully parsing the args ourselves is `--xdebug=` for step debugging.

**Comment by slucero** [comment]
I think it's fine having these as separate arguments giving the option to enable each independently or together. I vote for merging as-is.

**Pull request merged**
