### PR TITLE
Fix command table of contents links in readme.

### PR DESCRIPTION
**Pull request by slucero**
Fix anchor links in commands table of contents.

### CODE REVIEW

**Comment by gustavderdrache** [comment]
Is this a manual fix or part of the `oclif-dev readme` build command? If it's manual, this will break the next time we push a release.

**Comment by slucero** [comment]
Gross, I didn't know it was auto-generated. I manually updated it.

**Comment by gustavderdrache** [comment]
You're in luck, however - updates to `oclif-dev` make this unneeded - the next time we do a release, `README.md` will be updated. Let's close this and plan for a patch release instead.

**Comment by slucero** [comment]
Didn't see your last update and just came to the same conclusion as shown in the last commit. Your solution works for me, so I'll go ahead and close out this PR.

**Pull request closed without merging**
